version: '3'
services:
  redis:
    container_name: redis
    image: redis:7-alpine
    volumes: 
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
    ports:
      - "6380:6380"
    command: redis-server /usr/local/etc/redis/redis.conf